export const gifts_data = [
    {
        id: 'teste',
        name: 'teste',
        description: 'ja falei que é teste',
        category: 'lua-de-mel',
        price: 1,
        image: '../../img/listaPresente/engrenagem.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'aluguel-de-carro',
        name: 'Aluguel de carro',
        description: 'Aluguel de carro',
        category: 'lua-de-mel',
        price: 260,
        image: '../../img/listaPresente/luaDeMel/Aluguel Carro.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'champanhe-para-brindar-a-lua-de-mel',
        name: 'Champanhe para brindar a lua de mel',
        description: 'Champanhe para brindar a lua de mel',
        category: 'lua-de-mel',
        price: 206,
        image: '../../img/listaPresente/luaDeMel/chapanheLuaDeMel.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'jantar-privativo-na-areia',
        name: 'Jantar privativo na areia',
        description: 'Jantar privativo na areia',
        category: 'lua-de-mel',
        price: 227.48,
        image: '../../img/listaPresente/luaDeMel/jantarPeAreia.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },

    {
        id: 'brunch-no-hotel',
        name: 'Brunch no hotel',
        description: 'Brunch no hotel',
        category: 'lua-de-mel',
        price: 155.1,
        image: '../../img/listaPresente/luaDeMel/brunch.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'jantar-no-centro-historico',
        name: 'Jantar no centro histórico',
        description: 'Jantar no centro histórico',
        category: 'lua-de-mel',
        price: 206.8,
        image: '../../img/listaPresente/luaDeMel/jantarCentroHistorico.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'passeio-e-degustacao-na-vinicola',
        name: 'Passeio e degustação na vinícola',
        description: 'Passeio e degustação na vinícola',
        category: 'lua-de-mel',
        price: 206.8,
        image: '../../img/listaPresente/luaDeMel/degustacaoVinicola.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'noite-especial-com-queijos-e-vinhos',
        name: 'Noite especial com queijos e vinhos',
        description: 'Noite especial com queijos e vinhos',
        category: 'experiencias',
        price: 227.48,
        image: '../../img/listaPresente/experiencias/taboaDeQueijos.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'city-tour-pela-cidade',
        name: 'City tour pela cidade',
        description: 'City tour pela cidade',
        category: 'lua-de-mel',
        price: 310.21,
        image: '../../img/listaPresente/luaDeMel/tourCity.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'deixa-deus-te-usar',
        name: 'Deixa Deus te usar',
        description: 'Deixa Deus te usar',
        category: 'divertidos',
        price: 1034.02,
        image: '../../img/listaPresente/divertidos/deixaDeusUsar.jpeg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'patrocinio-oficial-da-lua-de-mel-completa',
        name: 'Patrocínio Oficial da Lua-de-Mel completa',
        description: 'Patrocínio Oficial da Lua-de-Mel completa',
        category: 'lua-de-mel',
        price: 1034.02,
        image: '../../img/listaPresente/luaDeMel/patrocinioLuaDeMel.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'ajuda-para-lua-de-mel',
        name: 'Ajuda para lua de mel',
        description: 'Ajuda para lua de mel',
        category: 'lua-de-mel',
        price: 150,
        image: '../../img/listaPresente/luaDeMel/ajudaLuaDeMel.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'assadeira',
        name: 'assadeira com fundo removivel',
        description: 'assadeira com fundo removivel',
        category: 'casa',
        price: 85.1,
        image: '../../img/listaPresente/casa/Assadeira fundo removivel.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'gravata-do-marido',
        name: 'Gravata do guerreiro',
        description: 'Gravata do guerreiro',
        category: 'divertidos',
        price: 100.1,
        image: '../../img/listaPresente/divertidos/gravata e tesoura.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'so-para-nao-dizer-que-eu-nao-dei-nada',
        name: 'Só para não dizer que eu não dei nada',
        description: 'Só para não dizer que eu não dei nada',
        category: 'divertidos',
        price: 155.1,
        image: '../../img/listaPresente/divertidos/soParaNaoDizer.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'cafe-da-manha-no-quarto',
        name: 'Café da manhã no quarto',
        description: 'Café da manhã no quarto',
        category: 'lua-de-mel',
        price: 180,
        image: '../../img/listaPresente/luaDeMel/cafeNoQuarto.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'diaria-no-hotel',
        name: 'Diária no hotel',
        description: 'Diária no hotel',
        category: 'lua-de-mel',
        price: 827.22,
        image: '../../img/listaPresente/luaDeMel/diariaHotel.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'jantar-romantico-na-lua-de-mel',
        name: 'Jantar romântico na lua de mel',
        description: 'Jantar romântico na lua de mel',
        category: 'lua-de-mel',
        price: 620.41,
        image: '../../img/listaPresente/luaDeMel/JantarRomanticoLua.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'adega-climatizada',
        name: 'Adega climatizada',
        description: 'Adega climatizada',
        category: 'eletro',
        price: 630.62,
        image: '../../img/listaPresente/eletro/adegaClimatizada.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'jantar-romantico-a-luz-de-velas',
        name: 'Jantar romântico a luz de velas',
        description: 'Jantar romântico a luz de velas',
        category: 'experiencias',
        price: 310.21,
        image: '../../img/listaPresente/experiencias/jantarVelas.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'spa-relaxante-para-o-casal',
        name: 'Spa relaxante para o casal',
        description: 'Spa relaxante para o casal',
        category: 'experiencias',
        price: 517.01,
        image: '../../img/listaPresente/experiencias/spaCasal.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'terapia-da-noiva-pos-preparativos-do-casamento',
        name: 'Terapia da noiva pós preparativos do casamento!',
        description: 'Terapia da noiva pós preparativos do casamento!',
        category: 'divertidos',
        price: 413.61,
        image: '../../img/listaPresente/divertidos/terapiaNoiva.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'passeio-de-barco-para-ver-golfinhos',
        name: 'Passeio de barco para ver golfinhos',
        description: 'Passeio de barco para ver golfinhos',
        category: 'experiencias',
        price: 300.01,
        image: '../../img/listaPresente/experiencias/passeioDeBarco.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'locacao-de-jetski',
        name: 'Locação de Jetski',
        description: 'Locação de Jetski',
        category: 'experiencias',
        price: 310.21,
        image: '../../img/listaPresente/experiencias/passeioJet.jpeg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'restaurante-submerso',
        name: 'Restaurante submerso',
        description: 'Restaurante submerso',
        category: 'experiencias',
        price: 450.21,
        image: '../../img/listaPresente/experiencias/restauranteSubmerso.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'cafe-da-manha-flutuante',
        name: 'Café da manhã flutuante',
        description: 'Café da manhã flutuante',
        category: 'experiencias',
        price: 261.91,
        image: '../../img/listaPresente/experiencias/cafeFlutuante.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'jantar-frutos-do-mar',
        name: 'Jantar frutos do mar',
        description: 'Jantar frutos do mar',
        category: 'experiencias',
        price: 413.61,
        image: '../../img/listaPresente/experiencias/jantarFrutosDoMar.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'aviaozinho-de-dinheiro-maoeee',
        name: 'Aviãozinho de dinheiro maôeee',
        description: 'Aviãozinho de dinheiro maôeee',
        category: 'divertidos',
        price: 155.1,
        image: '../../img/listaPresente/divertidos/aviaozinho.jpeg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'emprestimo-parcelado-para-pagar-a-festa',
        name: 'Empréstimo parcelado para pagar a festa',
        description: 'Empréstimo parcelado para pagar a festa',
        category: 'divertidos',
        price: 517.01,
        image: '../../img/listaPresente/divertidos/emprestimo.jpeg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'passeio-de-balao',
        name: 'Passeio de balão',
        description: 'Passeio de balão',
        category: 'experiencias',
        price: 568.71,
        image: '../../img/listaPresente/experiencias/passeioBalao.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'curso-de-como-fazer-arroz-e-feijao',
        name: 'Curso de como fazer arroz e feijão',
        description: 'Curso de como fazer arroz e feijão',
        category: 'divertidos',
        price: 206.8,
        image: '../../img/listaPresente/divertidos/arrozEfeijao.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'malas-para-a-lua-de-mel',
        name: 'Malas para a lua de mel',
        description: 'Malas para a lua de mel',
        category: 'lua-de-mel',
        price: 413.61,
        image: '../../img/listaPresente/luaDeMel/MalasLuaDeMel.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'vale-chinelo-e-oculos-para-o-casal-esquecidinho',
        name: 'Vale chinelo e óculos para o casal esquecidinho',
        description: 'Vale chinelo e óculos para o casal esquecidinho',
        category: 'divertidos',
        price: 155.1,
        image: '../../img/listaPresente/divertidos/chineloOculos.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'oculos-escuros-para-disfarcar-as-olheiras-no-dia-seguinte',
        name: 'Óculos escuros para disfarçar as olheiras no dia seguinte',
        description: 'Óculos escuros para disfarçar as olheiras no dia seguinte',
        category: 'divertidos',
        price: 310.21,
        image: '../../img/listaPresente/divertidos/oculosParaOlheiras.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'taxa-para-pedir-uma-musica-para-o-dj',
        name: 'Taxa para pedir uma música para o DJ',
        description: 'Taxa para pedir uma música para o DJ',
        category: 'divertidos',
        price: 100,
        image: '../../img/listaPresente/divertidos/pedirMusicaDj.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'manual-de-como-dobrar-roupa',
        name: 'Manual de como dobrar roupa',
        description: 'Manual de como dobrar roupa',
        category: 'divertidos',
        price: 150,
        image: '../../img/listaPresente/divertidos/roupaDobrada.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'vaquinha-para-programar-o-a-filho-a',
        name: 'Vaquinha para programar o(a) filho(a)',
        description: 'Vaquinha para programar o(a) filho(a)',
        category: 'divertidos',
        price: 1034.02,
        image: '../../img/listaPresente/divertidos/vaquinha.jpeg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'mesa-proxima-a-mesas-de-doces',
        name: 'Mesa próxima a mesas de doces',
        description: 'Mesa próxima a mesas de doces',
        category: 'divertidos',
        price: 206.8,
        image: '../../img/listaPresente/divertidos/mesaDeDoces.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'cota-para-os-noivos-se-amarem-para-sempre',
        name: 'Cota para os noivos se amarem para sempre',
        description: 'Cota para os noivos se amarem para sempre',
        category: 'divertidos',
        price: 413.61,
        image: '../../img/listaPresente/divertidos/amorParaSempre.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: '12-tacas-de-cristal-para-vinho',
        name: '12 taças de cristal para vinho',
        description: '12 taças de cristal para vinho',
        category: 'casa',
        price: 200,
        image: '../../img/listaPresente/casa/12tacasDeCristal.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'drinks-na-piscina',
        name: 'Drinks na piscina',
        description: 'Drinks na piscina',
        category: 'experiencias',
        price: 310.21,
        image: '../../img/listaPresente/experiencias/drinkPiscina.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'mc-do-casal',
        name: 'MC do casal',
        description: 'MC do casal',
        category: 'divertidos',
        price: 206.8,
        image: '../../img/listaPresente/divertidos/mcDoCasal.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'estoque-de-dorflex-para-as-tensoes-do-casamento',
        name: 'Estoque de Dorflex para as tensões do casamento',
        description: 'Estoque de Dorflex para as tensões do casamento',
        category: 'divertidos',
        price: 150.8,
        image: '../../img/listaPresente/divertidos/dorflex.png',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'drinks-no-bar-do-hotel',
        name: 'Drinks no bar',
        description: 'Drinks no bar do hotel',
        category: 'experiencias',
        price: 310.21,
        image: '../../img/listaPresente/experiencias/Bar.jpeg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'noite-de-pizza-na-lua-de-mel',
        name: 'Noite de Pizza na Lua de Mel',
        description: 'Noite de Pizza na Lua de Mel',
        category: 'lua-de-mel',
        price: 155.1,
        image: '../../img/listaPresente/luaDeMel/noiteDePizza.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'robo-aspirador-powerbot-e-samsung-2-em-1',
        name: 'Robô Aspirador Powerbot-e Samsung 2 em 1',
        description: 'Robô Aspirador Powerbot-e Samsung 2 em 1',
        category: 'eletro',
        price: 1091.49,
        image: '../../img/listaPresente/eletro/aspiradorSamsung.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'lava-loucas-brastemp',
        name: 'Lava Louças Brastemp',
        description: 'Lava Louças Brastemp Cinza Metálico com 08 Serviços',
        category: 'eletro',
        price: 1800.85,
        image: '../../img/listaPresente/eletro/lavaLoucas.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'colirio-pro-noivo-chorar-quando-a-noiva-entrar',
        name: 'Colírio pro noivo chorar quando a noiva entrar',
        description: 'Colírio pro noivo chorar quando a noiva entrar',
        category: 'divertidos',
        price: 160,
        image: '../../img/listaPresente/divertidos/colirio.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'panela-de-pressao-inox',
        name: 'Panela de pressão inox',
        description: 'Panela de pressão inox',
        category: 'casa',
        price: 250,
        image: '../../img/listaPresente/casa/panelaDePressao.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'panela-de-pressao-eletrica',
        name: 'Panela de pressão eletrica',
        description: 'Panela de pressão eletrica',
        category: 'casa',
        price: 422.57,
        image: '../../img/listaPresente/casa/panelaDePressaoEletrica.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'ferro-de-passar',
        name: 'Ferro de Passar',
        description: 'Ferro de Passar a Vapor e a Seco',
        category: 'eletro',
        price: 100,
        image: '../../img/listaPresente/eletro/ferroDePassar.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'faqueiro-com-30-pecas',
        name: 'Faqueiro com 30 peças',
        description: 'Faqueiro com 30 peças',
        category: 'casa',
        price: 368.71,
        image: '../../img/listaPresente/casa/faqueiroCom30.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'geladeira-frost-free',
        name: 'Geladeira Frost Free',
        description: 'Geladeira Frost Free',
        category: 'eletro',
        price: 3200.0,
        image: '../../img/listaPresente/eletro/geladeira.jpeg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'fogao-5-bocas',
        name: 'Fogão 5 Bocas',
        description: 'Fogão 5 Bocas',
        category: 'eletro',
        price: 1900.0,
        image: '../../img/listaPresente/eletro/Fogao.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'micro-ondas',
        name: 'Micro-ondas',
        description: 'Micro-ondas',
        category: 'eletro',
        price: 600.0,
        image: '../../img/listaPresente/eletro/Microondas.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'maquina-de-lavar',
        name: 'Máquina de Lavar',
        description: 'Máquina de Lavar',
        category: 'eletro',
        price: 2500.0,
        image: '../../img/listaPresente/eletro/LavaSeca.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'batedeira-planetaria',
        name: 'Batedeira Planetária',
        description: 'Batedeira Planetária',
        category: 'eletro',
        price: 350.0,
        image: '../../img/listaPresente/eletro/batedeiraPlanetaria.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'cafeteira-expresso',
        name: 'Cafeteira Expresso',
        description: 'Cafeteira Expresso',
        category: 'eletro',
        price: 450.0,
        image: '../../img/listaPresente/eletro/cafeteiraExpresso.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'liquidificador-de-alta-potencia',
        name: 'Liquidificador de Alta Potência',
        description: 'Liquidificador de Alta Potência',
        category: 'eletro',
        price: 220.0,
        image: '../../img/listaPresente/eletro/liquidificador.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'jogo-de-cama-casal',
        name: 'Jogo de Cama Casal',
        description: 'Jogo de Cama Casal',
        category: 'casa',
        price: 380.0,
        image: '../../img/listaPresente/casa/jogoDeCama.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'jogo-de-toalhas',
        name: 'Jogo de Toalhas',
        description: 'Jogo de Toalhas',
        category: 'casa',
        price: 250.0,
        image: '../../img/listaPresente/casa/jogoDeToalhas.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'jogo-de-panelas-antiaderente',
        name: 'Jogo de Panelas Antiaderente',
        description: 'Jogo de Panelas Antiaderente',
        category: 'casa',
        price: 550.0,
        image: '../../img/listaPresente/casa/jogoDePanelas.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'sofa-2-lugares',
        name: 'Sofá 2 Lugares',
        description: 'Sofá 2 Lugares',
        category: 'casa',
        price: 2800.0,
        image: '../../img/listaPresente/casa/sofa.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'quadro-decorativo-casal',
        name: 'Quadro Decorativo para o Casal',
        description: 'Quadro Decorativo para o Casal',
        category: 'casa',
        price: 180.0,
        image: '../../img/listaPresente/casa/quadroDecorativo.jpeg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'aula-de-culinaria-a-dois',
        name: 'Aula de Culinária a Dois',
        description: 'Aula de Culinária a Dois',
        category: 'experiencias',
        price: 350.0,
        image: '../../img/listaPresente/experiencias/aulaCulinaria.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'passeio-de-quadriciclo-na-lua-de-mel',
        name: 'Passeio de Quadriciclo na Lua de Mel',
        description: 'Passeio de Quadriciclo na Lua de Mel',
        category: 'lua-de-mel',
        price: 410.0,
        image: '../../img/listaPresente/luaDeMel/passeioQuadri.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'kit-toalha-de-praia-personalizada',
        name: 'Kit Toalha de Praia Personalizada',
        description: 'Kit Toalha de Praia Personalizada',
        category: 'lua-de-mel',
        price: 110.0,
        image: '../../img/listaPresente/luaDeMel/kitToalhaPraia.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'vale-brincadeira-quem-manda-na-relacao',
        name: 'Vale-brincadeira: Quem Manda na Relação',
        description: 'Vale-brincadeira: Quem Manda na Relação',
        category: 'divertidos',
        price: 130.0,
        image: '../../img/listaPresente/divertidos/mandaQuemPode.jpeg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
    {
        id: 'certificado-de-melhor-sogra-a',
        name: 'Certificado de Melhor Sogro(a)',
        description: 'Certificado de Melhor Sogro(a)',
        category: 'divertidos',
        price: 90.0,
        image: '../../img/listaPresente/divertidos/certificado.jpg',
        popularity: 0,
        dateAdded: '2026-07-22',
        funded: 0,
    },
];